---
title: "IVR_QC_count_GA Sample"
author: "Prabhat Gautam"
date: "7/17/2019""
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('knitr')
library('knitr')

install.packages("RODBC")
library('RODBC')

install.packages("dplyr")
library("dplyr")

install.packages("readxl")
library("readxl")

install.packages("readxl")
library("readxl")

install.packages("openxlsx")
library("openxlsx")

install.packages("purrr")
library("purrr")

```


```{r}
#Load the datasets into the individual frames if necessary and unable to load the environment below#
GA_1 <- read.delim("/Users/anthonygoss/Downloads/IVR_2018_export_ev_CR-7883_2019-04-16.txt")

# GA_long <- read.delim("C:/Users/prabh/Box/Data/Catalist sample data/IVR_2018_export_historical_GA.txt")

#Process and combine all datasets together#

#Union all the 3 pre-test outcomes#
#u_T1T2 <- union(T1c,T2c)
#u_all <- union(u_T1T2,T3c)
#u_all$OPEID_6TT <- paste(as.character(u_all$OPEID_6)," ",as.character(u_all$TT))
#
```

```{r}
#Generate frequencies of all the columns in the output of the dataframes unioned together-- replace the names for variables and the actual dataframe#
vars_12 <- c("CLASS", "MAJOR","GENDER")

R12_10_sub <- subset(R12_10, select = vars_12)

#This function below enables us to generate the frequencies and levels#
dt_res = data.frame()

for (i in 1:ncol(R12_10_sub)){

dt_temp = data.frame(t(table(R12_10_sub[,i])))
dt_temp$Var1 = names(R12_10_sub)[i]

dt_res = rbind(dt_res, dt_temp)

}

names(dt_res) = c("Variable","Levels","Freq")


```

```{r}
#Load the environment from the directory-- change the path accordingly#
load("C:/Users//Box/Data/Catalist sample data/IVR sample data.RData")

```

```{r}
#Use the responses in order to generate ifelse logic to create the syntax necessary
# You can concatenate ANID with subgroup just to keep unique individual within a subgroup.
GA_1$ANIDsub <- paste(GA_1$ANID,GA_1$subgroup)

#The following code can be used in order to de-duplicate the record based on required date or registration# 
GA_1a <- GA_1[order(GA_1$ANIDsub,GA_1$requireddate
 , decreasing=TRUE),]
#Keep only the first row for the duplicate of UNIQUE_ID
GA_1b <- GA_1a[!duplicated(GA_1a$ANIDsub),]
```

```{r}
#Coding chunk, which assigns indicator for all records#
GA_1b$id <- ifelse(GA_1b$ANIDsub == ' ',0,1)

#Matched to Current or Historic VF- based on typecode alone#
GA_1b$matched<-ifelse(GA_1b$global_typecode == 'No match'| GA_1b$global_typecode == ' ', 0, 1)

#Successful Registrants- I noticed that everyone has required registration date in GA sample. I used voter status to code if someone is active or inactive as registered#
GA_1b$registered <- ifelse(GA_1b$voterstatus == 'active' |
                          GA_1b$voterstatus == 'inactive', 1, 0)

#1. Based on the methodology document- successful registrant is referred to as information provided at the registration also matching contemporary voter file
#2. are the input registration status passed through to the final file?
#3. There is a table referred to in the syntax typecode_codes_detailed table-- how was this constructed

#Successful Registrants based on global typecode#
GA_1b$success <- ifelse(GA_1b$global_typecode == 'First time registrant' | GA_1b$global_typecode == 'Cross-state move' | GA_1b$global_typecode == 'In-state move in-county'| GA_1b$global_typecode == 'In-state move cross-county'| GA_1b$global_typecode == 'Status change' |GA_1b$global_typecode == 'Date change'| GA_1b$global_typecode == 'No change unregistered',1,0)

#Roll Changing Registrants#
GA_1b$roll_ch <- ifelse(GA_1b$global_typecode == 'First time registrant' | GA_1b$global_typecode == 'Cross-state move' | GA_1b$global_typecode == 'In-state move in-county'| GA_1b$global_typecode == 'In-state move cross-county'| GA_1b$global_typecode == 'Status change' |GA_1b$global_typecode == 'Date change',1,0)

#New Registrants#
GA_1b$new_reg <- ifelse(GA_1b$global_typecode == 'First time registrant', 1,0)

#Pending Registrants#
GA_1b$pending <- ifelse(GA_1b$success == 0 | GA_1b$roll_ch == 0,
                       1,0)

#2018 Voters#
GA_1b$voted <- ifelse(GA_1b$es_n2018g == 'N' |
                       GA_1b$es_n2018g == 'Z'|
                       GA_1b$es_n2018g == 'U', 0, 1)
```

```{r}
#Coding chunk which assigns the above categories to those who voted#

#Voted and successful#
GA_1b$success_v <- ifelse(GA_1b$success == 1 | GA_1b$voted == 1, 1,0)

#Voted and Roll Changed#
GA_1b$roll_v <- ifelse(GA_1b$roll_ch == 1 | GA_1b$voted == 1,1,0)

#New Registrants and voted#
GA_1b$newreg_v <- ifelse(GA_1b$new_reg == 1 | GA_1b$voted == 1, 1,0)

#Pending and voted#
GA_1b$pending_v <- ifelse(GA_1b$pending == 1 | GA_1b$voted
                         == 1,1,0)
```

```{r}
#Number of times a record has occured in the database and which is that record#
n_occur <- data.frame(table(GA_1$ANID))
names(n_occur)[names(n_occur)=="Var1"] <- "ANID"

n_occur_1 <- n_occur[n_occur$Freq == 1,]

n_occur_2 <- n_occur[n_occur$Freq == 2,]

n_occur_3 <- n_occur[n_occur$Freq == 3,]

n_occur_4 <- n_occur[n_occur$Freq == 4,]

n_occur_5 <- n_occur[n_occur$Freq == 5,]

n_occur_6more <- n_occur[n_occur$Freq > 5,]

#Merge the number of times UNIQUEID occurs with the original dataframe#
GA_1c <- Reduce(function(dtf1,dtf2)merge(dtf1,dtf2, by = "ANID", all.x=TRUE),
                      list(GA_1b,n_occur))

#Create indicator variables based on the above freq field#
GA_1c$`>1`<-ifelse(GA_1c$Freq != 1, 1, 0)

```


```{r}
#Code below to group by sub-group type using dplyr#
library("dplyr")
subgroup <- GA_1c %>% group_by(subgroup)

#Summarize across the entire file#
sub_group_output <- subgroup %>% summarise(
  unique = sum(id),
  `>1_r` = mean(`>1`),
  `>1` = sum(`>1`),
  success_r = mean(success),
  roll_ch_r = mean(roll_ch),
  new_reg_r = mean(new_reg),
  pend_r = mean(pending),
  vr =mean(voted),
  success = sum(success),
  roll_ch = sum(roll_ch),
  new_reg = sum(new_reg),
  pend = sum(pending),
  voted =sum(voted),
  success_v_r = mean(success_v),
  roll_ch_v_r = mean(roll_v),
  new_reg_v_r = mean(newreg_v),
  pend_v_r = mean(pending_v),
  success_v = sum(success_v),
  roll_ch_v = sum(roll_v),
  new_reg_v = sum(newreg_v),
  pend_v = sum(pending_v)
  )
```

```{r}
#Code below to group by sub-group and program_type type using dplyr#
library("dplyr")
subgroup2 <- GA_1c %>% group_by(subgroup,program_type)

#Summarize across the entire file#
sub_group_prg_output <- subgroup2 %>% summarise(
  unique = sum(id),
  `>1_r` = mean(`>1`),
  `>1` = sum(`>1`),
  success_r = mean(success),
  roll_ch_r = mean(roll_ch),
  new_reg_r = mean(new_reg),
  pend_r = mean(pending),
  vr =mean(voted),
  success = sum(success),
  roll_ch = sum(roll_ch),
  new_reg = sum(new_reg),
  pend = sum(pending),
  voted =sum(voted),
  success_v_r = mean(success_v),
  roll_ch_v_r = mean(roll_v),
  new_reg_v_r = mean(newreg_v),
  pend_v_r = mean(pending_v),
  success_v = sum(success_v),
  roll_ch_v = sum(roll_v),
  new_reg_v = sum(newreg_v),
  pend_v = sum(pending_v)
  )

```

```{r}
#Code below to group by sub-group and program_type type using dplyr#
library("dplyr")
subgroup3 <- GA_1c %>% group_by(org,program_type)

#Summarize across the entire file#
org_prgtype_output <- subgroup3 %>% summarise(
  unique = sum(id),
  `>1_r` = mean(`>1`),
  `>1` = sum(`>1`),
  success_r = mean(success),
  roll_ch_r = mean(roll_ch),
  new_reg_r = mean(new_reg),
  pend_r = mean(pending),
  vr =mean(voted),
  success = sum(success),
  roll_ch = sum(roll_ch),
  new_reg = sum(new_reg),
  pend = sum(pending),
  voted =sum(voted),
  success_v_r = mean(success_v),
  roll_ch_v_r = mean(roll_v),
  new_reg_v_r = mean(newreg_v),
  pend_v_r = mean(pending_v),
  success_v = sum(success_v),
  roll_ch_v = sum(roll_v),
  new_reg_v = sum(newreg_v),
  pend_v = sum(pending_v)
  )

```


```{r}
#Write out all the outputs from above into one excel document#
library("openxlsx")

#Create workbook and sheets with names#
GA_sample_QC <- createWorkbook()
addWorksheet(GA_sample_QC, "sub_group_output")
addWorksheet(GA_sample_QC, "sub_group_prg_output")
addWorksheet(GA_sample_QC, "org_prgtype_output")

#Write output tables into the sheets#
writeDataTable(GA_sample_QC, "sub_group_output", x = sub_group_output)
writeDataTable(GA_sample_QC, "sub_group_prg_output", x = sub_group_prg_output)
writeDataTable(GA_sample_QC, "org_prgtype_output", x = org_prgtype_output)

saveWorkbook(GA_sample_QC, "GA_Sample_QC_output_7.22.19.xlsx",overwrite = TRUE)

```


```{r}
#Save your global environment prior to quitting#
save.image(file='IVR sample data.RData')

```